### ISSUE TITLE
Unable to install module "celery"

### ISSUE THREAD

**Issue by omushpapa** [novacode-nl/odoo-celery#25] opened 2019-11-08 05:49 UTC
I am getting `Unable to install module "celery" because an external dependency is not met: No module named celery` when trying to install the module on Odoo 12 with python 3.6.5

**Comment by bobslee** [comment] 2019-11-08 13:49
The required Python package *celery* needs to be installed - also mentioned in documentation.

On commandline: 

pip install celery

If it not works..due to pip linking with Python2.7, try:

pip3 install celery

**Comment by omushpapa** [comment] 2019-11-09 06:34
I should have given more information. The python package `celery` is already installed on Odoo's python environment. On installing this module, Odoo's [_check_external_dependencies](https://github.com/odoo/odoo/blob/c9bedcc0efc71d71e26410db2ec1db1f4009a0b6/odoo/addons/base/models/ir_module.py#L316) runs `importlib.import_module('celery')` which raises
```python
# This is run in PyCharm's debug mode
Traceback (most recent call last):
  File "/home/aswa/applications/pycharm-community-2019.1.3/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/aswa/.local/share/virtualenvs/twelve-YNQc9i_8/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aswa/v12_dev/celery/__init__.py", line 4, in <module>
    from . import odoo
  File "/home/aswa/applications/pycharm-community-2019.1.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/aswa/v12_dev/celery/odoo.py", line 6, in <module>
    from celery import Celery
ImportError: cannot import name 'Celery'
```
In my belief, the line `from celery import Celery` imports this Odoo module instead of the Python module. The issue being that both modules have the same name.

I believe, the resolution would be changing the Odoo module's name from celery to odoo_celery

**Comment by bobslee** [comment] 2019-11-09 08:41
Hi @giantas, thanks for the info.

Several projects which use this module (v10, v11, v12), never encountered such error before.
I even just tested the complete module with a Celery worker started - No error.
So that's quite odd :)

Again I've some questions:

1. On which Operating System (and release) you installed Odoo and run the Celery worker on?

2. I don't expect, but maybe it's module version related. So please let me know which version of the Odoo module you use (expect the latest?)

3. When does the problem occur? Upon starting the Odoo server or Celery worker(s)?

4. I also ponder whether this problem is PyCharm (IDE) related. Maybe PyCharm mingles with the PYTHONPATH ?
If not yet, try to run the Odoo server and Celery worker with commandline. Please Let me know the outcome.

I won't change the module name, because there's no reason and I can't reproduce.

Let's hope we can solve your issue :)

**Comment by bobslee** [comment] 2019-11-14 21:55
@giantas are you able to provide me the info?
Would like to analyse this issue further.

**Comment by bobslee** [comment] 2019-11-29 22:15
I closed this report. It's not obvious or reproducable without extra information.

**Closed as completed** 2019-11-29 22:14 UTC
